name: Publish

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            linux,
            windows,
            macos
        ]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/<name>
            asset_name: <name>-linux
          - name: windows
            os: windows-latest
            artifact_name: target/release/<name>.exe
            asset_name: <name>-windows
          - name: macos
            os: macos-latest
            artifact_name: target/release/<name>
            asset_name: <name>-macos

    steps:
    - uses: actions/checkout@v2.3.4 
    - uses: actions-rs/toolchain@v1.0.6
      with:
        profile: minimal
        toolchain: stable
        default: true
        override: true

    - name: Build
      uses: actions-rs/cargo@v1.0.1
      with:
          command: build
          args: --release --locked

    - name: Upload binaries to release
      uses: actions/upload-artifact@v2.2.0
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}